import type { MediaItem, PortalUser, Review, ReviewComment } from "./types";

export const demoUsers: PortalUser[] = [
  { id: "u1", name: "Demo User", email: "user@ngv.local", role: "user", password: "user123" },
  { id: "a1", name: "Admin", email: "admin@ngv.local", role: "admin", password: "admin123" },
];

export const mediaSeed: MediaItem[] = [
  {
    id: "1",
    title: "The Dark Knight Returns",
    synopsis: "When evil rises, a hero must answer.",
    genres: ["Action", "Drama"],
    releaseYear: 2024,
    director: "Nolan Reeve",
    cast: ["A. Khan", "S. Rahman", "M. Hossain"],
    platforms: ["NGV"],
    pricing: "premium",
    streamingUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    poster: "https://images.unsplash.com/photo-1739891251370-05b62a54697b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    duration: "2h 45m",
    avgRating: 8.9,
    totalReviews: 120,
  },
  {
    id: "2",
    title: "Mystery at Midnight",
    synopsis: "A detective uncovers a conspiracy in the city.",
    genres: ["Thriller", "Mystery"],
    releaseYear: 2024,
    director: "R. Sen",
    cast: ["N. Haque", "R. Paul"],
    platforms: ["NGV", "Prime Video"],
    pricing: "free",
    streamingUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    poster: "https://images.unsplash.com/photo-1595171694538-beb81da39d3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    duration: "1h 58m",
    avgRating: 8.5,
    totalReviews: 89,
  },
  {
    id: "3",
    title: "Cinema Paradiso",
    synopsis: "A moving love letter to cinema and memory.",
    genres: ["Drama", "Classic"],
    releaseYear: 2023,
    director: "T. Alam",
    cast: ["A. Noor", "K. Islam"],
    platforms: ["NGV", "Netflix"],
    pricing: "premium",
    streamingUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    poster: "https://images.unsplash.com/photo-1616527546362-bf6b7f80a751?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    duration: "2h 15m",
    avgRating: 9.2,
    totalReviews: 156,
  },
  {
    id: "4",
    title: "Portrait of Shadows",
    synopsis: "A mysterious portrait changes everyone who sees it.",
    genres: ["Mystery", "Horror"],
    releaseYear: 2023,
    director: "J. Karim",
    cast: ["S. Akter", "M. Reza"],
    platforms: ["NGV", "Disney+"],
    pricing: "free",
    streamingUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    poster: "https://images.unsplash.com/photo-1590707642683-8a2e8d713c60?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    duration: "1h 42m",
    avgRating: 8.1,
    totalReviews: 64,
  },
];

export const reviewSeed: Review[] = [
  {
    id: "r1",
    mediaId: "1",
    userId: "u1",
    userName: "Demo User",
    rating: 9,
    content: "Brilliant pacing and action. Must watch.",
    tags: ["classic", "family-friendly"],
    spoiler: false,
    isPublished: true,
    likes: 4,
    likedBy: ["u1"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "r2",
    mediaId: "1",
    userId: "u1",
    userName: "Demo User",
    rating: 8,
    content: "Second half was intense. Ending surprised me.",
    tags: ["underrated"],
    spoiler: true,
    isPublished: false,
    likes: 0,
    likedBy: [],
    createdAt: new Date().toISOString(),
  },
];

export const commentSeed: ReviewComment[] = [
  {
    id: "c1",
    reviewId: "r1",
    userId: "u1",
    userName: "Demo User",
    content: "Agree! Sound design was top notch.",
    isPublished: true,
    createdAt: new Date().toISOString(),
  },
];
